// <auto-generated />
using EF_05_MonAn;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_05_MonAn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230801101059_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_05_MonAn.Models.CongThuc", b =>
                {
                    b.Property<int>("CongthucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongthucID"));

                    b.Property<string>("Donvitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonanID")
                        .HasColumnType("int");

                    b.Property<int>("NguyenlieuID")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("CongthucID");

                    b.HasIndex("MonanID");

                    b.HasIndex("NguyenlieuID");

                    b.ToTable("CongThuc");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.LoaiMonAn", b =>
                {
                    b.Property<int>("LoaimonanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaimonanID"));

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaimonanID");

                    b.ToTable("LoaiMonAn");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.MonAn", b =>
                {
                    b.Property<int>("MonanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonanID"));

                    b.Property<string>("Cachlam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Giaban")
                        .HasColumnType("int");

                    b.Property<string>("Gioithieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaimonanID")
                        .HasColumnType("int");

                    b.Property<string>("Tenmon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonanID");

                    b.HasIndex("LoaimonanID");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenlieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenlieuID"));

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennguyenlieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguyenlieuID");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.CongThuc", b =>
                {
                    b.HasOne("EF_05_MonAn.Models.MonAn", "MonAn")
                        .WithMany("CongThuc")
                        .HasForeignKey("MonanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_05_MonAn.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("CongThuc")
                        .HasForeignKey("NguyenlieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.MonAn", b =>
                {
                    b.HasOne("EF_05_MonAn.Models.LoaiMonAn", "LoaiMonAn")
                        .WithMany("MonAn")
                        .HasForeignKey("LoaimonanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMonAn");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.LoaiMonAn", b =>
                {
                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.MonAn", b =>
                {
                    b.Navigation("CongThuc");
                });

            modelBuilder.Entity("EF_05_MonAn.Models.NguyenLieu", b =>
                {
                    b.Navigation("CongThuc");
                });
#pragma warning restore 612, 618
        }
    }
}
