// <auto-generated />
using EF_02_NhanVien.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_02_NhanVien.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230722071934_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_02_NhanVien.Models.DuAn", b =>
                {
                    b.Property<int>("DuanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuanID"));

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenduan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DuanID");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("EF_02_NhanVien.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanvienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanvienID"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hesoluong")
                        .HasColumnType("int");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanvienID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("EF_02_NhanVien.Models.PhanCong", b =>
                {
                    b.Property<int>("PhancongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhancongID"));

                    b.Property<int>("DuanID")
                        .HasColumnType("int");

                    b.Property<int>("NhanvienID")
                        .HasColumnType("int");

                    b.Property<int>("Sogiolam")
                        .HasColumnType("int");

                    b.HasKey("PhancongID");

                    b.HasIndex("DuanID");

                    b.HasIndex("NhanvienID");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("EF_02_NhanVien.Models.PhanCong", b =>
                {
                    b.HasOne("EF_02_NhanVien.Models.DuAn", "DuAn")
                        .WithMany("phanCongs")
                        .HasForeignKey("DuanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_02_NhanVien.Models.NhanVien", "NhanVien")
                        .WithMany("phanCongs")
                        .HasForeignKey("NhanvienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("EF_02_NhanVien.Models.DuAn", b =>
                {
                    b.Navigation("phanCongs");
                });

            modelBuilder.Entity("EF_02_NhanVien.Models.NhanVien", b =>
                {
                    b.Navigation("phanCongs");
                });
#pragma warning restore 612, 618
        }
    }
}
